"""
NYAYA AI — PDF Generation Service
Generates downloadable legal documents as PDFs
"""
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch, cm
from reportlab.lib.colors import HexColor, black, white
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from loguru import logger


BRAND_CYAN = HexColor("#00b4d8")
BRAND_DARK = HexColor("#03045e")
BRAND_LIGHT = HexColor("#f0f4f8")
BRAND_GRAY = HexColor("#6b7280")


class PDFGeneratorService:

    def generate_legal_document(
        self,
        title: str,
        content: str,
        doc_type: str,
        user_name: str = "",
        metadata: dict = None,
    ) -> bytes:
        """Generate a professionally formatted legal document PDF"""
        buffer = io.BytesIO()

        doc = SimpleDocTemplate(
            buffer,
            pagesize=A4,
            rightMargin=2*cm,
            leftMargin=2.5*cm,
            topMargin=2*cm,
            bottomMargin=2*cm,
        )

        styles = getSampleStyleSheet()
        story = []

        # Header style
        header_style = ParagraphStyle(
            "Header",
            parent=styles["Normal"],
            fontSize=9,
            textColor=BRAND_GRAY,
            alignment=TA_RIGHT,
        )

        # Title style
        title_style = ParagraphStyle(
            "DocTitle",
            parent=styles["Normal"],
            fontSize=16,
            fontName="Helvetica-Bold",
            textColor=BRAND_DARK,
            alignment=TA_CENTER,
            spaceAfter=6,
        )

        # Subtitle style
        subtitle_style = ParagraphStyle(
            "SubTitle",
            parent=styles["Normal"],
            fontSize=10,
            textColor=BRAND_GRAY,
            alignment=TA_CENTER,
            spaceAfter=12,
        )

        # Body style
        body_style = ParagraphStyle(
            "Body",
            parent=styles["Normal"],
            fontSize=11,
            leading=18,
            textColor=black,
            alignment=TA_JUSTIFY,
            spaceAfter=8,
        )

        # Section header style
        section_style = ParagraphStyle(
            "Section",
            parent=styles["Normal"],
            fontSize=12,
            fontName="Helvetica-Bold",
            textColor=BRAND_DARK,
            spaceBefore=12,
            spaceAfter=6,
        )

        # ─── HEADER ───────────────────────────────────────────────
        story.append(Paragraph(
            f"Generated by NYAYA AI | {datetime.now().strftime('%d %B %Y')} | nyaya-ai.in",
            header_style
        ))
        story.append(HRFlowable(width="100%", thickness=2, color=BRAND_CYAN, spaceAfter=12))

        # ─── TITLE ────────────────────────────────────────────────
        story.append(Paragraph(title.upper(), title_style))
        story.append(Paragraph(
            f"Under the Laws of India | For: {user_name or 'Applicant'}",
            subtitle_style
        ))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_GRAY, spaceAfter=20))

        # ─── BODY CONTENT ─────────────────────────────────────────
        # Process content - split by lines and format
        lines = content.split('\n')
        for line in lines:
            line = line.strip()
            if not line:
                story.append(Spacer(1, 6))
                continue

            # Detect headers (lines ending with : or ALL CAPS)
            if line.endswith(':') and len(line) < 80:
                story.append(Paragraph(line, section_style))
            elif line.isupper() and len(line) < 80:
                story.append(Paragraph(line, section_style))
            elif line.startswith('•') or line.startswith('-') or line.startswith('*'):
                bullet_style = ParagraphStyle(
                    "Bullet",
                    parent=body_style,
                    leftIndent=20,
                    bulletIndent=10,
                )
                story.append(Paragraph(f"• {line.lstrip('•-* ')}", bullet_style))
            elif line[0].isdigit() and line[1] in '.):':
                # Numbered list
                story.append(Paragraph(line, body_style))
            else:
                story.append(Paragraph(line, body_style))

        # ─── FOOTER ───────────────────────────────────────────────
        story.append(Spacer(1, 20))
        story.append(HRFlowable(width="100%", thickness=0.5, color=BRAND_GRAY))
        story.append(Spacer(1, 8))

        footer_data = [
            [
                Paragraph("<b>NYAYA AI</b> | Free Legal Aid Platform", ParagraphStyle("FL", fontSize=8, textColor=BRAND_GRAY)),
                Paragraph("📞 NALSA Free Legal Aid: <b>15100</b>", ParagraphStyle("FR", fontSize=8, textColor=BRAND_GRAY, alignment=TA_RIGHT)),
            ]
        ]
        footer_table = Table(footer_data, colWidths=[10*cm, 8*cm])
        story.append(footer_table)

        disclaimer_style = ParagraphStyle(
            "Disclaimer",
            parent=styles["Normal"],
            fontSize=7,
            textColor=BRAND_GRAY,
            alignment=TA_CENTER,
            spaceBefore=6,
        )
        story.append(Paragraph(
            "DISCLAIMER: This document is generated for informational purposes. "
            "Please consult a qualified lawyer before filing. NYAYA AI does not provide legal representation.",
            disclaimer_style
        ))

        # Build PDF
        doc.build(story)
        pdf_bytes = buffer.getvalue()
        buffer.close()
        return pdf_bytes

    def generate_rti_pdf(self, user_details: dict, case_details: dict, content: str) -> bytes:
        """Generate RTI application PDF"""
        return self.generate_legal_document(
            title="Application Under Right to Information Act, 2005",
            content=content,
            doc_type="rti",
            user_name=user_details.get("name", ""),
            metadata=case_details,
        )

    def generate_complaint_pdf(self, user_details: dict, case_details: dict, content: str, complaint_type: str) -> bytes:
        """Generate complaint PDF"""
        titles = {
            "consumer": "Complaint Before District Consumer Commission",
            "labour": "Complaint Before Labour Commissioner",
            "police": "Police Complaint / FIR Application",
            "domestic_violence": "Application Under Domestic Violence Act 2005",
        }
        return self.generate_legal_document(
            title=titles.get(complaint_type, "Legal Complaint"),
            content=content,
            doc_type=complaint_type,
            user_name=user_details.get("name", ""),
        )


pdf_service = PDFGeneratorService()
